//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGCI_WPF_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string matricule { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> fuction { get; set; }
    
        public virtual fonction fonction { get; set; }
    }
}
